FROM rust:1.75.0 as builder

WORKDIR /app
COPY . .

RUN cargo build


FROM rust:1.75.0

WORKDIR /app
COPY --from=builder /app/target/debug/s3-cdn .
COPY --from=builder /app/.env .

ENV TZ="Asia/Tokyo"

CMD ["./s3-cdn"]
EXPOSE 8000:8000